create table projects (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    root_path varchar(1000) not null,
    description varchar(1000),
    created_at timestamp with time zone not null
);

create table code_files (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects(id) on delete cascade,
    path varchar(1200) not null,
    file_name varchar(255) not null,
    language varchar(30) not null,
    is_test boolean not null,
    size_bytes bigint not null,
    last_modified_at timestamp with time zone not null
);

create table code_symbols (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects(id) on delete cascade,
    file_id bigint not null references code_files(id) on delete cascade,
    name varchar(255) not null,
    type varchar(30) not null,
    role varchar(80),
    package_name varchar(500),
    start_line integer,
    end_line integer,
    annotations varchar(10000),
    imports varchar(10000)
);

create index idx_code_files_project_id on code_files(project_id);
create index idx_code_files_project_path on code_files(project_id, path);
create index idx_code_symbols_project_id on code_symbols(project_id);
create index idx_code_symbols_file_id on code_symbols(file_id);
create index idx_code_symbols_name on code_symbols(project_id, name);
create index idx_code_symbols_role on code_symbols(project_id, role);
