create table bug_reports (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects(id) on delete cascade,
    title varchar(200) not null,
    description varchar(10000) not null,
    status varchar(30) not null,
    created_at timestamp with time zone not null
);

create index idx_bug_reports_project_id on bug_reports(project_id);
create index idx_bug_reports_project_status on bug_reports(project_id, status);
create index idx_bug_reports_created_at on bug_reports(created_at);
