DO $$
DECLARE
    report_row RECORD;
    new_bug_id BIGINT;
BEGIN
    IF to_regclass('public.bugs') IS NULL THEN
        RETURN;
    END IF;

    ALTER TABLE bugs ADD COLUMN IF NOT EXISTS message TEXT;
    ALTER TABLE bugs ADD COLUMN IF NOT EXISTS stack_trace JSONB;
    ALTER TABLE bugs ADD COLUMN IF NOT EXISTS raw_payload JSONB;
    ALTER TABLE bugs ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMPTZ;
    ALTER TABLE bugs ALTER COLUMN title DROP NOT NULL;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'bugs' AND column_name = 'occurrence_count'
    ) THEN
        ALTER TABLE bugs ALTER COLUMN occurrence_count DROP NOT NULL;
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'bugs' AND column_name = 'first_seen_at'
    ) THEN
        ALTER TABLE bugs ALTER COLUMN first_seen_at DROP NOT NULL;
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'bugs' AND column_name = 'last_seen_at'
    ) THEN
        ALTER TABLE bugs ALTER COLUMN last_seen_at DROP NOT NULL;
    END IF;

    -- Legacy decision snapshots cannot be mapped to a root workflow run reliably.
    DROP TABLE IF EXISTS bug_grouping_decisions CASCADE;
    DROP TABLE IF EXISTS bug_match_decisions CASCADE;
    DROP TABLE IF EXISTS agent_operations CASCADE;

    -- Preserve legacy analysis snapshots by converting their jobs into workflow runs.
    IF to_regclass('public.analysis_jobs') IS NOT NULL THEN
        IF to_regclass('public.analysis_results') IS NOT NULL THEN
            ALTER TABLE analysis_results RENAME TO legacy_analysis_results;
        END IF;
        ALTER TABLE analysis_jobs RENAME TO legacy_analysis_jobs;

        CREATE TABLE IF NOT EXISTS agent_workflow_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            project_id BIGINT NOT NULL REFERENCES projects(id),
            request_id VARCHAR(255) NOT NULL,
            request_type VARCHAR(80) NOT NULL,
            request_hash VARCHAR(64) NOT NULL,
            status VARCHAR(30) NOT NULL,
            request_payload JSONB NOT NULL,
            latest_checkpoint JSONB,
            result_snapshot JSONB,
            failure_code VARCHAR(100),
            failure_message VARCHAR(2000),
            started_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            version BIGINT NOT NULL DEFAULT 0,
            CONSTRAINT uk_workflow_runs_project_request UNIQUE (project_id, request_id)
        );

        CREATE TEMP TABLE legacy_analysis_workflow_map (
            analysis_job_id BIGINT PRIMARY KEY,
            workflow_run_id BIGINT NOT NULL
        ) ON COMMIT DROP;

        FOR report_row IN SELECT * FROM legacy_analysis_jobs ORDER BY id LOOP
            INSERT INTO agent_workflow_runs (
                project_id,
                request_id,
                request_type,
                request_hash,
                status,
                request_payload,
                result_snapshot,
                failure_code,
                failure_message,
                started_at,
                completed_at,
                created_at,
                updated_at,
                version
            ) VALUES (
                report_row.project_id,
                'legacy-analysis-job-' || report_row.id,
                'analyze_issue',
                md5('legacy-analysis-job-' || report_row.id)
                    || md5('legacy-analysis-job-' || report_row.id || ':hash'),
                report_row.status::text,
                jsonb_build_object(
                    'issue_id', report_row.issue_id,
                    'trigger_bug_id', report_row.bug_id,
                    'legacy_analysis_job_id', report_row.id
                ),
                NULL,
                CASE WHEN report_row.status::text = 'FAILED' THEN 'LEGACY_ANALYSIS_FAILED' END,
                report_row.failure_reason,
                report_row.started_at,
                report_row.completed_at,
                report_row.created_at,
                COALESCE(report_row.completed_at, report_row.started_at, report_row.created_at),
                0
            ) RETURNING id INTO new_bug_id;

            INSERT INTO legacy_analysis_workflow_map(analysis_job_id, workflow_run_id)
            VALUES (report_row.id, new_bug_id);
        END LOOP;

        CREATE TABLE analysis_results (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workflow_run_id BIGINT NOT NULL UNIQUE REFERENCES agent_workflow_runs(id),
            issue_id BIGINT NOT NULL REFERENCES issues(id),
            previous_analysis_result_id BIGINT REFERENCES analysis_results(id),
            status VARCHAR(30) NOT NULL,
            result_snapshot JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL
        );

        IF to_regclass('public.legacy_analysis_results') IS NOT NULL THEN
            INSERT INTO analysis_results (
                workflow_run_id,
                issue_id,
                previous_analysis_result_id,
                status,
                result_snapshot,
                created_at
            )
            SELECT workflow.workflow_run_id,
                   job.issue_id,
                   NULL,
                   legacy.status::text,
                   (legacy.result_snapshot - 'analysis_job_id')
                       || jsonb_build_object('workflow_run_id', workflow.workflow_run_id),
                   legacy.created_at
            FROM legacy_analysis_results legacy
            JOIN legacy_analysis_jobs job ON job.id = legacy.job_id
            JOIN legacy_analysis_workflow_map workflow ON workflow.analysis_job_id = job.id
            WHERE job.issue_id IS NOT NULL;

            UPDATE agent_workflow_runs run
            SET result_snapshot = result.result_snapshot
            FROM analysis_results result
            WHERE result.workflow_run_id = run.id;

            UPDATE analysis_results current_result
            SET previous_analysis_result_id = previous_result.id
            FROM legacy_analysis_results legacy,
                 legacy_analysis_workflow_map current_workflow,
                 legacy_analysis_workflow_map previous_workflow,
                 analysis_results previous_result
            WHERE current_workflow.analysis_job_id = legacy.job_id
              AND current_result.workflow_run_id = current_workflow.workflow_run_id
              AND legacy.previous_analysis_job_id IS NOT NULL
              AND previous_workflow.analysis_job_id = legacy.previous_analysis_job_id
              AND previous_result.workflow_run_id = previous_workflow.workflow_run_id;

            UPDATE analysis_results
            SET result_snapshot = jsonb_set(
                result_snapshot,
                '{revision_summary}',
                (result_snapshot->'revision_summary' - 'previous_analysis_job_id')
                    || jsonb_build_object(
                        'previous_analysis_result_id', previous_analysis_result_id
                    )
            )
            WHERE previous_analysis_result_id IS NOT NULL
              AND result_snapshot->'revision_summary' IS NOT NULL;

            DROP TABLE legacy_analysis_results;
        END IF;
        DROP TABLE legacy_analysis_jobs;
    END IF;

    IF to_regclass('public.bug_reports') IS NOT NULL THEN
        ALTER TABLE bug_reports ADD COLUMN IF NOT EXISTS migrated_bug_id BIGINT;

        -- The earliest report reuses its former aggregate Bug id.
        WITH ranked AS (
            SELECT report.id,
                   report.bug_id,
                   ROW_NUMBER() OVER (
                       PARTITION BY report.bug_id
                       ORDER BY report.occurred_at, report.id
                   ) AS report_rank
            FROM bug_reports report
            WHERE report.bug_id IS NOT NULL
        )
        UPDATE bug_reports report
        SET migrated_bug_id = ranked.bug_id
        FROM ranked
        WHERE report.id = ranked.id
          AND ranked.report_rank = 1;

        UPDATE bugs bug
        SET source = report.source,
            title = report.title,
            description = report.description,
            error_type = report.error_type,
            message = report.message,
            stack_trace = COALESCE(report.stack_trace, '[]'::jsonb),
            raw_payload = report.raw_payload,
            occurred_at = report.occurred_at
        FROM bug_reports report
        WHERE report.migrated_bug_id = bug.id;

        -- Every remaining collected report becomes its own Bug.
        FOR report_row IN
            SELECT *
            FROM bug_reports
            WHERE migrated_bug_id IS NULL
            ORDER BY id
        LOOP
            INSERT INTO bugs (
                project_id,
                title,
                description,
                source,
                error_type,
                message,
                stack_trace,
                raw_payload,
                occurred_at,
                status,
                severity,
                created_at,
                updated_at
            ) VALUES (
                report_row.project_id,
                report_row.title,
                report_row.description,
                report_row.source,
                report_row.error_type,
                report_row.message,
                COALESCE(report_row.stack_trace, '[]'::jsonb),
                report_row.raw_payload,
                report_row.occurred_at,
                'NEW',
                NULL,
                COALESCE(report_row.created_at, CURRENT_TIMESTAMP),
                COALESCE(report_row.created_at, CURRENT_TIMESTAMP)
            ) RETURNING id INTO new_bug_id;

            UPDATE bug_reports
            SET migrated_bug_id = new_bug_id
            WHERE id = report_row.id;

            -- Preserve the Issue membership of reports that shared a legacy aggregate Bug.
            IF report_row.bug_id IS NOT NULL AND to_regclass('public.issue_bugs') IS NOT NULL THEN
                INSERT INTO issue_bugs (issue_id, bug_id, confidence, grouped_by, created_at)
                SELECT link.issue_id,
                       new_bug_id,
                       link.confidence,
                       link.grouped_by,
                       COALESCE(report_row.created_at, CURRENT_TIMESTAMP)
                FROM issue_bugs link
                WHERE link.bug_id = report_row.bug_id
                ON CONFLICT DO NOTHING;
            END IF;
        END LOOP;

        DROP TABLE bug_reports CASCADE;
    END IF;

    UPDATE bugs
    SET stack_trace = COALESCE(stack_trace, '[]'::jsonb),
        occurred_at = COALESCE(occurred_at, first_seen_at, created_at, CURRENT_TIMESTAMP),
        message = COALESCE(message, normalized_message)
    WHERE stack_trace IS NULL OR occurred_at IS NULL OR message IS NULL;

    ALTER TABLE bugs ALTER COLUMN stack_trace SET NOT NULL;
    ALTER TABLE bugs ALTER COLUMN occurred_at SET NOT NULL;
    ALTER TABLE bugs DROP COLUMN IF EXISTS reporter_name;
    ALTER TABLE bugs DROP COLUMN IF EXISTS normalized_message;
    ALTER TABLE bugs DROP COLUMN IF EXISTS top_application_frame;
    ALTER TABLE bugs DROP COLUMN IF EXISTS occurrence_count;
    ALTER TABLE bugs DROP COLUMN IF EXISTS first_seen_at;
    ALTER TABLE bugs DROP COLUMN IF EXISTS last_seen_at;

    IF to_regclass('public.issues') IS NOT NULL THEN
        ALTER TABLE issues DROP COLUMN IF EXISTS occurrence_count;
        IF to_regclass('public.issue_bugs') IS NOT NULL THEN
            UPDATE issues issue
            SET bug_count = aggregate.bug_count,
                first_seen_at = aggregate.first_seen_at,
                last_seen_at = aggregate.last_seen_at
            FROM (
                SELECT link.issue_id,
                       COUNT(*) AS bug_count,
                       MIN(bug.occurred_at) AS first_seen_at,
                       MAX(bug.occurred_at) AS last_seen_at
                FROM issue_bugs link
                JOIN bugs bug ON bug.id = link.bug_id
                GROUP BY link.issue_id
            ) aggregate
            WHERE issue.id = aggregate.issue_id;
        END IF;
    END IF;

    CREATE INDEX IF NOT EXISTS idx_bugs_project_occurred
        ON bugs (project_id, occurred_at);
END
$$;
