create table analysis_jobs (
    id bigint generated by default as identity primary key,
    report_id bigint not null references bug_reports(id) on delete cascade,
    status varchar(30) not null,
    created_at timestamp with time zone not null,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    failure_reason varchar(1000),
    importance_score integer,
    difficulty_score integer,
    risk_score integer,
    issue_type varchar(500),
    keywords varchar(1000),
    domains varchar(1000),
    summary varchar(2000),
    related_code varchar(10000),
    rationale varchar(4000),
    recommended_fix varchar(4000),
    recommended_tests varchar(4000)
);

create index idx_analysis_jobs_report_id on analysis_jobs(report_id);
create index idx_analysis_jobs_status on analysis_jobs(status);
